MAX_SEARCH_DEPTH=25
DIRECTORY_EXCLUSIONS=synopsys,clion,cmake,toolchains,docker,buildArm,buildUbuntu,Tools,BuildSystem,TestSystem,UnitTests,ISG_Shared,pugixml

detect.detector.search.depth=${MAX_SEARCH_DEPTH}
detect.excluded.directories.search.depth=${MAX_SEARCH_DEPTH}
detect.excluded.directories=${DIRECTORY_EXCLUSIONS}

detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
detect.blackduck.signature.scanner.copyright.search=true
detect.blackduck.signature.scanner.license.search=true
detect.blackduck.signature.scanner.individual.file.matching=ALL
detect.blackduck.signature.scanner.upload.source.mode=true
detect.blackduck.signature.scanner.exclusion.name.patterns=tests,boost,pugixml,UnitTests,TestSystem,ISG_Shared
